// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNnAeJrldicqIKybgcfU-SmDy56KfLGp8',
    appId: '1:198449566099:web:4c49568e77efa0ce5c1866',
    messagingSenderId: '198449566099',
    projectId: 'my-nusantara-project',
    authDomain: 'my-nusantara-project.firebaseapp.com',
    storageBucket: 'my-nusantara-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg-PycLwzZ95QiB-pl9-oCuz0B_YuApiY',
    appId: '1:198449566099:android:f70c829a71a5a3d35c1866',
    messagingSenderId: '198449566099',
    projectId: 'my-nusantara-project',
    storageBucket: 'my-nusantara-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqnjVt8WS5bzz79xx3q11kkGJoDDpKEm0',
    appId: '1:198449566099:ios:1f2b477499e1db005c1866',
    messagingSenderId: '198449566099',
    projectId: 'my-nusantara-project',
    storageBucket: 'my-nusantara-project.appspot.com',
    iosBundleId: 'com.example.wildlifego',
  );
}
